#!/bin/bash

mkdir -p aurora/Aurora/AuroraDotNetEngine
mkdir -p aurora/Aurora/AuroraDotNetEngine4
mkdir -p aurora/OpenSim/Framework/Servers/HttpServer
mkdir -p aurora/OpenSim/Region/CoreModules/Avatar/Groups
mkdir -p aurora/OpenSim/Region/CoreModules/Agent/AssetTransaction
mkdir -p aurora/OpenSim/Region/CoreModules/World/Land
mkdir -p aurora/OpenSim/Region/CoreModules/World/Objects/BuySell
mkdir -p aurora/OpenSim/Region/CoreModules/Agent/AssetTransaction
mkdir -p aurora/OpenSim/Services/CapsService/CAPModules
mkdir -p aurora/Aurora/Modules/World/SampleCurrencyModule
mkdir -p aurora/Aurora/Modules/Avatar/AuroraProfile


mkdir -p aurora-/Aurora/AuroraDotNetEngine
mkdir -p aurora-/Aurora/AuroraDotNetEngine4
mkdir -p aurora-/OpenSim/Framework/Servers/HttpServer
mkdir -p aurora-/OpenSim/Region/CoreModules/Avatar/Groups
mkdir -p aurora-/OpenSim/Region/CoreModules/Agent/AssetTransaction
mkdir -p aurora-/OpenSim/Region/CoreModules/World/Land
mkdir -p aurora-/OpenSim/Region/CoreModules/World/Objects/BuySell
mkdir -p aurora-/OpenSim/Region/CoreModules/Agent/AssetTransaction
mkdir -p aurora-/OpenSim/Services/CapsService/CAPModules
mkdir -p aurora-/Aurora/Modules/World/SampleCurrencyModule
mkdir -p aurora-/Aurora/Modules/Avatar/AuroraProfile
